// backend/evals/dataset/components/angular/counter.component.ts
import { Component, Input, OnInit } from '@angular/core'

@Component({
  selector: 'app-counter',
  template: `
    <div class="counter">
      <h2>Count: {{ count }}</h2>
      <p>{{ isEven ? 'Even' : 'Odd' }}</p>
      <button (click)="decrement()">-</button>
      <button (click)="increment()">+</button>
      <button (click)="reset()">Reset</button>
    </div>
  `,
})
export class CounterComponent implements OnInit {
  @Input() initial: number = 0
  @Input() step: number = 1
  count: number = 0

  get isEven(): boolean {
    return this.count % 2 === 0
  }

  ngOnInit(): void {
    this.count = this.initial
  }

  increment(): void {
    this.count += this.step
  }

  decrement(): void {
    this.count -= this.step
  }

  reset(): void {
    this.count = this.initial
  }
}

// backend/evals/dataset/components/react/counter.jsx
import { useState } from 'react'

export default function Counter({ initial = 0, step = 1 }) {
  const [count, setCount] = useState(initial)
  const isEven = count % 2 === 0

  const increment = () => setCount(c => c + step)
  const decrement = () => setCount(c => c - step)
  const reset = () => setCount(initial)

  return (
    <div className="counter">
      <h2>Count: {count}</h2>
      <p>{isEven ? 'Even' : 'Odd'}</p>
      <button onClick={decrement}>-</button>
      <button onClick={increment}>+</button>
      <button onClick={reset}>Reset</button>
    </div>
  )
}
