// backend/evals/dataset/components/vue/todo_list.vue
<template>
  <div class="todo-list">
    <h2>{{ title }}</h2>
    <input v-model="newTodo" placeholder="What needs doing?" />
    <button @click="addTodo">Add</button>
    <p v-if="todos.length === 0">No todos yet</p>
    <ul v-else>
      <li v-for="todo in todos" :key="todo.id" :class="{ done: todo.done }">
        <input type="checkbox" :checked="todo.done" @change="toggleTodo(todo.id)" />
        <span>{{ todo.text }}</span>
        <button @click="removeTodo(todo.id)">Delete</button>
      </li>
    </ul>
    <p>{{ remaining }} remaining</p>
  </div>
</template>

<script>
export default {
  name: 'TodoList',
  props: {
    title: { type: String, default: 'My Todos' },
  },
  data() {
    return {
      todos: [],
      newTodo: '',
    }
  },
  computed: {
    remaining() {
      return this.todos.filter(t => !t.done).length
    },
  },
  methods: {
    addTodo() {
      const text = this.newTodo.trim()
      if (!text) return
      this.todos.push({ id: Date.now(), text, done: false })
      this.newTodo = ''
    },
    toggleTodo(id) {
      const todo = this.todos.find(t => t.id === id)
      if (todo) todo.done = !todo.done
    },
    removeTodo(id) {
      this.todos = this.todos.filter(t => t.id !== id)
    },
  },
}
</script>

<style scoped>
.done span {
  text-decoration: line-through;
}
</style>

// backend/evals/dataset/components/react/todo_list.jsx
import { useState, useMemo } from 'react'

export default function TodoList({ title = 'My Todos' }) {
  const [todos, setTodos] = useState([])
  const [newTodo, setNewTodo] = useState('')
  const remaining = useMemo(() => todos.filter(t => !t.done).length, [todos])

  const addTodo = () => {
    const text = newTodo.trim()
    if (!text) return
    setTodos([...todos, { id: Date.now(), text, done: false }])
    setNewTodo('')
  }

  const toggleTodo = (id) => {
    setTodos(todos.map(t => (t.id === id ? { ...t, done: !t.done } : t)))
  }

  const removeTodo = (id) => {
    setTodos(todos.filter(t => t.id !== id))
  }

  return (
    <div className="todo-list">
      <h2>{title}</h2>
      <input
        value={newTodo}
        onChange={e => setNewTodo(e.target.value)}
        placeholder="What needs doing?"
      />
      <button onClick={addTodo}>Add</button>
      {todos.length === 0 ? (
        <p>No todos yet</p>
      ) : (
        <ul>
          {todos.map(todo => (
            <li key={todo.id} className={todo.done ? 'done' : ''}>
              <input
                type="checkbox"
                checked={todo.done}
                onChange={() => toggleTodo(todo.id)}
              />
              <span>{todo.text}</span>
              <button onClick={() => removeTodo(todo.id)}>Delete</button>
            </li>
          ))}
        </ul>
      )}
      <p>{remaining} remaining</p>
    </div>
  )
}
