// backend/evals/judge_calibration/timer_html_react_correct_hidden.jsx
import { useState, useEffect } from 'react'

function formatTime(total) {
  const m = String(Math.floor(total / 60)).padStart(2, '0')
  const s = String(total % 60).padStart(2, '0')
  return m + ':' + s
}

export default function SessionTimer({ label = 'Session', limit = 60 }) {
  const [seconds, setSeconds] = useState(0)

  useEffect(() => {
    const intervalId = setInterval(() => setSeconds(s => s + 1), 1000)
    return () => clearInterval(intervalId)
  }, [])

  const reset = () => setSeconds(0)

  return (
    <div className="session-timer">
      <h2>{label}</h2>
      <p className="time">{formatTime(seconds)}</p>
      <p className="warning" hidden={seconds < limit}>Time's up!</p>
      <button onClick={reset}>Reset</button>
    </div>
  )
}

// backend/evals/judge_calibration/timer_html_vue_correct_hidden.vue
<template>
  <div class="session-timer">
    <h2>Session</h2>
    <p class="time">{{ formatTime(seconds) }}</p>
    <p class="warning" :hidden="seconds < LIMIT">Time's up!</p>
    <button @click="reset">Reset</button>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

const LIMIT = 60
const seconds = ref(0)
let intervalId = null

function formatTime(total) {
  const m = String(Math.floor(total / 60)).padStart(2, '0')
  const s = String(total % 60).padStart(2, '0')
  return m + ':' + s
}

function reset() {
  seconds.value = 0
}

onMounted(() => {
  intervalId = setInterval(() => {
    seconds.value++
  }, 1000)
})

onUnmounted(() => {
  clearInterval(intervalId)
})
</script>
